thin = "─│┌┐└┘├┤┬┴┼"
thin_thick = "─│┌┐└┘├┤┬┴┼┝━┿┥"
thin_double = "─│┌┐└┘├┤┬┴┼╞═╪╡"
rounded = "─│╭╮╰╯├┤┬┴┼"
rounded_thick = "─│╭╮╰╯├┤┬┴┼┝━┿┥"
rounded_double = "─│╭╮╰╯├┤┬┴┼╞═╪╡"
thick = "━┃┏┓┗┛┣┫┳┻╋"
thick_thin = "─│┌┐└┘├┤┬┴┼┠─╂┨"
double = "═║╔╗╚╝╠╣╦╩╬"
double_thin = "═║╔╗╚╝╠╣╦╩╬╟─╫╢"

thin_ascii = "-|+++++++++"
thin_double_ascii = "-|++++++++++=++"
double_ascii = "=H+++++++++"
double_thin_ascii = "=H++++++++++-++"
