thin = "─│┌┐└┘├┤┬┴┼"
thin_thick = "─│┌┐└┘├┤┬┴┼┝━┿┥"
thin_double = "─│┌┐└┘├┤┬┴┼╞═╪╡"
rounded = "─│╭╮╰╯├┤┬┴┼"
rounded_thick = "─│╭╮╰╯├┤┬┴┼┝━┿┥"
rounded_double = "─│╭╮╰╯├┤┬┴┼╞═╪╡"
thick = "━┃┏┓┗┛┣┫┳┻╋"
thick_thin = "─│┌┐└┘├┤┬┴┼┠─╂┨"
double = "═║╔╗╚╝╠╣╦╩╬"
double_thin = "═║╔╗╚╝╠╣╦╩╬╟─╫╢"
booktabs = "─       ─── ━━ "

ascii_thin = "-|+++++++++"
ascii_thin_double = "-|++++++++++=++"
ascii_double = "=H+++++++++"
ascii_double_thin = "=H++++++++++-++"
ascii_booktabs = "-       --- == "
